### ISSUE TITLE
How about the repo?

### ISSUE THREAD

**Issue by imcuttle** [wre232114/enhanced-tsconfig-paths-webpack-plugin#1]
I had same question about nested tsconfig in webpack

**Comment by wre232114** [comment]
I am working on this project, will finish the first version this week

**Comment by wre232114** [comment]
@imcuttle version 0.1.0 is published, please refer to README for usage

**Comment by imcuttle** [comment]
@wre232114  有一些优化点：
0. issuer 存在没有的情况，需要兼容
1. console.log 可以隐藏起来，通过 verbose 传参判断是否需要 log
2. 感觉可以外部配置一下 issuer 的 include 和 exclude；如对于 node_modules 资源不希望走这套逻辑

**Comment by wre232114** [comment]
@imcuttle 是的，这些点需要优化。include 和 exclude 这些需要处理，以及 tsconfig path 的匹配逻辑支持参数配置，处理开启类型检查时的编译报错等等，这些后面会做，可以一起合作

**Comment by wre232114** [comment]
> @wre232114 有一些优化点：
> 0. issuer 存在没有的情况，需要兼容
> 
> 1. console.log 可以隐藏起来，通过 verbose 传参判断是否需要 log
> 2. 感觉可以外部配置一下 issuer 的 include 和 exclude；如对于 node_modules 资源不希望走这套逻辑

这个 [PR 3](https://github.com/wre232114/enhanced-tsconfig-paths-webpack-plugin/pull/3) 增加了是否忽略 node_modules 的配置项，默认是 true。下个 PR 会添加更详细的 include 和 exclude 配置
